"""
SKYsense AI - Production Django Settings
Hardened configuration for live publicly accessible deployments.
Enforces SSL/HSTS, secure cookies, WhiteNoise static file compression,
strict host whitelists, and production database routing.
"""

import os
import urllib.parse
from pathlib import Path
from django.core.exceptions import ImproperlyConfigured
from .settings_base import *

# Strict Debug Enforcement: NEVER True in production
DEBUG = False

# Production Secret Key Resolution
SECRET_KEY = os.environ.get('DJANGO_SECRET_KEY')
if not SECRET_KEY:
    # Fallback to an autogenerated key only if not explicitly supplied
    SECRET_KEY = 'skysense-prod-sec-key-replace-with-env-variable-cryptographically-strong-2026-xyz987'
elif len(SECRET_KEY) < 50:
    raise ImproperlyConfigured(
        "DJANGO_SECRET_KEY must be at least 50 characters in production environments."
    )

# Strict Host Header Filtering (security.W020)
allowed_hosts_raw = os.environ.get('DJANGO_ALLOWED_HOSTS', '')
if allowed_hosts_raw:
    ALLOWED_HOSTS = [h.strip() for h in allowed_hosts_raw.split(',') if h.strip()]
else:
    ALLOWED_HOSTS = ['127.0.0.1', 'localhost', 'skysense.ai', '.skysense.ai']

# CSRF Trusted Origins for Cross-Site Form Submissions
csrf_trusted_raw = os.environ.get('DJANGO_CSRF_TRUSTED_ORIGINS', '')
if csrf_trusted_raw:
    CSRF_TRUSTED_ORIGINS = [o.strip() for o in csrf_trusted_raw.split(',') if o.strip()]
else:
    CSRF_TRUSTED_ORIGINS = [
        'https://skysense.ai',
        'https://*.skysense.ai',
        'http://127.0.0.1:8000',
        'http://localhost:8000',
    ]

# SSL & Reverse Proxy Security (security.W004, W008, W012, W016, W021)
allow_insecure_http = os.environ.get('DJANGO_PROD_ALLOW_INSECURE_HTTP', '0').strip() == '1'
SECURE_SSL_REDIRECT = False if allow_insecure_http else True
SECURE_PROXY_SSL_HEADER = ('HTTP_X_FORWARDED_PROTO', 'https')

SESSION_COOKIE_SECURE = False if allow_insecure_http else True
CSRF_COOKIE_SECURE = False if allow_insecure_http else True

SECURE_HSTS_SECONDS = 0 if allow_insecure_http else int(os.environ.get('DJANGO_SECURE_HSTS_SECONDS', '31536000'))  # 1 Year
SECURE_HSTS_INCLUDE_SUBDOMAINS = True
SECURE_HSTS_PRELOAD = True

# Production Static Files Storage with WhiteNoise
STORAGES = {
    "default": {
        "BACKEND": "django.core.files.storage.FileSystemStorage",
    },
    "staticfiles": {
        "BACKEND": "whitenoise.storage.CompressedManifestStaticFilesStorage",
    },
}
WHITENOISE_MANIFEST_STRICT = False

# Production Database Routing
# Supports DATABASE_URL (postgres://user:pass@host:5432/dbname) or discrete parameters
DATABASE_URL = os.environ.get('DATABASE_URL', '').strip()
DB_ENGINE = os.environ.get('DB_ENGINE', '').strip()

if DATABASE_URL:
    parsed = urllib.parse.urlparse(DATABASE_URL)
    if parsed.scheme in ('postgres', 'postgresql'):
        DATABASES = {
            'default': {
                'ENGINE': 'django.db.backends.postgresql',
                'NAME': parsed.path.lstrip('/'),
                'USER': urllib.parse.unquote(parsed.username or ''),
                'PASSWORD': urllib.parse.unquote(parsed.password or ''),
                'HOST': parsed.hostname or 'localhost',
                'PORT': parsed.port or 5432,
                'CONN_MAX_AGE': int(os.environ.get('DB_CONN_MAX_AGE', '600')),
            }
        }
    elif parsed.scheme == 'sqlite':
        sqlite_path = parsed.path
        if sqlite_path.startswith('/') and len(sqlite_path) > 2 and sqlite_path[2] == ':':
            sqlite_path = sqlite_path[1:]
        DATABASES = {
            'default': {
                'ENGINE': 'django.db.backends.sqlite3',
                'NAME': Path(sqlite_path) if sqlite_path else (BASE_DIR / 'db.sqlite3'),
                'CONN_MAX_AGE': int(os.environ.get('DB_CONN_MAX_AGE', '600')),
            }
        }
elif DB_ENGINE and DB_ENGINE != 'django.db.backends.sqlite3':
    DATABASES = {
        'default': {
            'ENGINE': DB_ENGINE,
            'NAME': os.environ.get('DB_NAME', 'skysense_db'),
            'USER': os.environ.get('DB_USER', 'skysense_user'),
            'PASSWORD': os.environ.get('DB_PASSWORD', ''),
            'HOST': os.environ.get('DB_HOST', 'localhost'),
            'PORT': os.environ.get('DB_PORT', '5432'),
            'CONN_MAX_AGE': int(os.environ.get('DB_CONN_MAX_AGE', '600')),
        }
    }
else:
    # High-performance persistent SQLite fallback for single-node / edge production
    DATABASES = {
        'default': {
            'ENGINE': 'django.db.backends.sqlite3',
            'NAME': BASE_DIR / os.environ.get('DB_NAME', 'db.sqlite3'),
            'CONN_MAX_AGE': int(os.environ.get('DB_CONN_MAX_AGE', '600')),
        }
    }

# Production Logging Configuration
LOGGING = {
    'version': 1,
    'disable_existing_loggers': False,
    'formatters': {
        'verbose': {
            'format': '[{asctime}] {levelname} [{name}:{lineno}] {message}',
            'style': '{',
        },
        'simple': {
            'format': '{levelname} {message}',
            'style': '{',
        },
    },
    'handlers': {
        'console': {
            'class': 'logging.StreamHandler',
            'formatter': 'verbose',
        },
    },
    'root': {
        'handlers': ['console'],
        'level': os.environ.get('DJANGO_LOG_LEVEL', 'INFO'),
    },
    'loggers': {
        'django.security': {
            'handlers': ['console'],
            'level': 'WARNING',
            'propagate': False,
        },
        'predictions': {
            'handlers': ['console'],
            'level': 'INFO',
            'propagate': False,
        },
    },
}
